[features]
seeds = false
skip-lint = false
[programs.localnet]
cluster_lend = "E9Jcn8HfLEc9dG6VmPQqHhwqKEJNRUc1VLFhrvxdgkx9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sadao/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
